"use client";
import { FormEvent, useState } from "react";
type Fields = { name: string; email: string; type: string; description: string; schedule: string; budget: string; links: string };
const initial: Fields = { name: "", email: "", type: "", description: "", schedule: "", budget: "", links: "" };
export function ContactForm() { const [fields, setFields] = useState(initial); const [errors, setErrors] = useState<Partial<Fields>>({}); const [success, setSuccess] = useState(false); const update = (key: keyof Fields, value: string) => setFields((old) => ({ ...old, [key]: value }));
  const submit = (event: FormEvent) => { event.preventDefault(); const next: Partial<Fields> = {}; if (!fields.name.trim()) next.name = "Please tell us your name."; if (!/^\S+@\S+\.\S+$/.test(fields.email)) next.email = "Enter a valid email address."; if (!fields.type) next.type = "Choose a project type."; if (!fields.description.trim()) next.description = "Tell us a little about the project."; setErrors(next); if (Object.keys(next).length) return; setSuccess(true); };
  if (success) return <div className="form-success" role="status"><strong>Your signal has entered Orrery.</strong><p>This launch form is a client-side demonstration only. Connect the submission adapter to your chosen email or form provider before publishing.</p><button className="button secondary" onClick={() => { setSuccess(false); setFields(initial); }}>Send another signal</button></div>;
  return <form className="contact-form" onSubmit={submit} noValidate>{Object.keys(errors).length > 0 && <div className="form-summary" role="alert">Please correct the highlighted fields before continuing.</div>}<div className="field"><label htmlFor="name">Name</label><input id="name" value={fields.name} onChange={(e) => update("name", e.target.value)} aria-invalid={!!errors.name} aria-describedby={errors.name ? "name-error" : undefined}/>{errors.name && <span id="name-error" className="field-error">{errors.name}</span>}</div><div className="field"><label htmlFor="email">Email</label><input id="email" type="email" value={fields.email} onChange={(e) => update("email", e.target.value)} aria-invalid={!!errors.email} aria-describedby={errors.email ? "email-error" : undefined}/>{errors.email && <span id="email-error" className="field-error">{errors.email}</span>}</div><div className="field"><label htmlFor="type">Project type</label><select id="type" value={fields.type} onChange={(e) => update("type", e.target.value)} aria-invalid={!!errors.type}><option value="">Select one</option><option>Original music</option><option>Rhythm-game composition</option><option>Game or interactive media</option><option>Arrangement or production</option><option>Artistic collaboration</option><option>Creative technology</option><option>Other</option></select>{errors.type && <span className="field-error">{errors.type}</span>}</div><div className="field"><label htmlFor="description">Short project description</label><textarea id="description" value={fields.description} onChange={(e) => update("description", e.target.value)} aria-invalid={!!errors.description}/>{errors.description && <span className="field-error">{errors.description}</span>}</div><div className="field"><label htmlFor="schedule">Approximate schedule</label><input id="schedule" value={fields.schedule} onChange={(e) => update("schedule", e.target.value)}/></div><div className="field"><label htmlFor="budget">Budget range <span className="quiet">(optional)</span></label><input id="budget" value={fields.budget} onChange={(e) => update("budget", e.target.value)}/></div><div className="field"><label htmlFor="links">Relevant links <span className="quiet">(optional)</span></label><input id="links" value={fields.links} onChange={(e) => update("links", e.target.value)}/></div><button className="button" type="submit">Send a signal</button></form>;
}
